# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/fun_security_sys

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/fun_security_sys

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/fun_security_sys/CMakeFiles /home/pi/fun_security_sys//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/fun_security_sys/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named train

# Build rule for target.
train: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 train
.PHONY : train

# fast build rule for target.
train/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/build
.PHONY : train/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/cameraEventHandler.o: src/cameraEventHandler.cpp.o

.PHONY : src/cameraEventHandler.o

# target to build an object file
src/cameraEventHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/cameraEventHandler.cpp.o
.PHONY : src/cameraEventHandler.cpp.o

src/cameraEventHandler.i: src/cameraEventHandler.cpp.i

.PHONY : src/cameraEventHandler.i

# target to preprocess a source file
src/cameraEventHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/cameraEventHandler.cpp.i
.PHONY : src/cameraEventHandler.cpp.i

src/cameraEventHandler.s: src/cameraEventHandler.cpp.s

.PHONY : src/cameraEventHandler.s

# target to generate assembly for a file
src/cameraEventHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/cameraEventHandler.cpp.s
.PHONY : src/cameraEventHandler.cpp.s

src/faceRecogitionTraining.o: src/faceRecogitionTraining.cpp.o

.PHONY : src/faceRecogitionTraining.o

# target to build an object file
src/faceRecogitionTraining.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/src/faceRecogitionTraining.cpp.o
.PHONY : src/faceRecogitionTraining.cpp.o

src/faceRecogitionTraining.i: src/faceRecogitionTraining.cpp.i

.PHONY : src/faceRecogitionTraining.i

# target to preprocess a source file
src/faceRecogitionTraining.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/src/faceRecogitionTraining.cpp.i
.PHONY : src/faceRecogitionTraining.cpp.i

src/faceRecogitionTraining.s: src/faceRecogitionTraining.cpp.s

.PHONY : src/faceRecogitionTraining.s

# target to generate assembly for a file
src/faceRecogitionTraining.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/train.dir/build.make CMakeFiles/train.dir/src/faceRecogitionTraining.cpp.s
.PHONY : src/faceRecogitionTraining.cpp.s

src/ledEventHandler.o: src/ledEventHandler.cpp.o

.PHONY : src/ledEventHandler.o

# target to build an object file
src/ledEventHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ledEventHandler.cpp.o
.PHONY : src/ledEventHandler.cpp.o

src/ledEventHandler.i: src/ledEventHandler.cpp.i

.PHONY : src/ledEventHandler.i

# target to preprocess a source file
src/ledEventHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ledEventHandler.cpp.i
.PHONY : src/ledEventHandler.cpp.i

src/ledEventHandler.s: src/ledEventHandler.cpp.s

.PHONY : src/ledEventHandler.s

# target to generate assembly for a file
src/ledEventHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ledEventHandler.cpp.s
.PHONY : src/ledEventHandler.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sg90EventHandler.o: src/sg90EventHandler.cpp.o

.PHONY : src/sg90EventHandler.o

# target to build an object file
src/sg90EventHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/sg90EventHandler.cpp.o
.PHONY : src/sg90EventHandler.cpp.o

src/sg90EventHandler.i: src/sg90EventHandler.cpp.i

.PHONY : src/sg90EventHandler.i

# target to preprocess a source file
src/sg90EventHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/sg90EventHandler.cpp.i
.PHONY : src/sg90EventHandler.cpp.i

src/sg90EventHandler.s: src/sg90EventHandler.cpp.s

.PHONY : src/sg90EventHandler.s

# target to generate assembly for a file
src/sg90EventHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/sg90EventHandler.cpp.s
.PHONY : src/sg90EventHandler.cpp.s

src/soundEventHandler.o: src/soundEventHandler.cpp.o

.PHONY : src/soundEventHandler.o

# target to build an object file
src/soundEventHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/soundEventHandler.cpp.o
.PHONY : src/soundEventHandler.cpp.o

src/soundEventHandler.i: src/soundEventHandler.cpp.i

.PHONY : src/soundEventHandler.i

# target to preprocess a source file
src/soundEventHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/soundEventHandler.cpp.i
.PHONY : src/soundEventHandler.cpp.i

src/soundEventHandler.s: src/soundEventHandler.cpp.s

.PHONY : src/soundEventHandler.s

# target to generate assembly for a file
src/soundEventHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/soundEventHandler.cpp.s
.PHONY : src/soundEventHandler.cpp.s

src/ws2811EventHandler.o: src/ws2811EventHandler.cpp.o

.PHONY : src/ws2811EventHandler.o

# target to build an object file
src/ws2811EventHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ws2811EventHandler.cpp.o
.PHONY : src/ws2811EventHandler.cpp.o

src/ws2811EventHandler.i: src/ws2811EventHandler.cpp.i

.PHONY : src/ws2811EventHandler.i

# target to preprocess a source file
src/ws2811EventHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ws2811EventHandler.cpp.i
.PHONY : src/ws2811EventHandler.cpp.i

src/ws2811EventHandler.s: src/ws2811EventHandler.cpp.s

.PHONY : src/ws2811EventHandler.s

# target to generate assembly for a file
src/ws2811EventHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ws2811EventHandler.cpp.s
.PHONY : src/ws2811EventHandler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... train"
	@echo "... src/cameraEventHandler.o"
	@echo "... src/cameraEventHandler.i"
	@echo "... src/cameraEventHandler.s"
	@echo "... src/faceRecogitionTraining.o"
	@echo "... src/faceRecogitionTraining.i"
	@echo "... src/faceRecogitionTraining.s"
	@echo "... src/ledEventHandler.o"
	@echo "... src/ledEventHandler.i"
	@echo "... src/ledEventHandler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sg90EventHandler.o"
	@echo "... src/sg90EventHandler.i"
	@echo "... src/sg90EventHandler.s"
	@echo "... src/soundEventHandler.o"
	@echo "... src/soundEventHandler.i"
	@echo "... src/soundEventHandler.s"
	@echo "... src/ws2811EventHandler.o"
	@echo "... src/ws2811EventHandler.i"
	@echo "... src/ws2811EventHandler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

