# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/raspi_project_16

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/raspi_project_16

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/raspi_project_16/CMakeFiles /home/pi/raspi_project_16//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/raspi_project_16/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/dispatchEventService.o: src/dispatchEventService.cpp.o

.PHONY : src/dispatchEventService.o

# target to build an object file
src/dispatchEventService.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/dispatchEventService.cpp.o
.PHONY : src/dispatchEventService.cpp.o

src/dispatchEventService.i: src/dispatchEventService.cpp.i

.PHONY : src/dispatchEventService.i

# target to preprocess a source file
src/dispatchEventService.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/dispatchEventService.cpp.i
.PHONY : src/dispatchEventService.cpp.i

src/dispatchEventService.s: src/dispatchEventService.cpp.s

.PHONY : src/dispatchEventService.s

# target to generate assembly for a file
src/dispatchEventService.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/dispatchEventService.cpp.s
.PHONY : src/dispatchEventService.cpp.s

src/event.o: src/event.cpp.o

.PHONY : src/event.o

# target to build an object file
src/event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/event.cpp.o
.PHONY : src/event.cpp.o

src/event.i: src/event.cpp.i

.PHONY : src/event.i

# target to preprocess a source file
src/event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/event.cpp.i
.PHONY : src/event.cpp.i

src/event.s: src/event.cpp.s

.PHONY : src/event.s

# target to generate assembly for a file
src/event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/event.cpp.s
.PHONY : src/event.cpp.s

src/events_def.o: src/events_def.cpp.o

.PHONY : src/events_def.o

# target to build an object file
src/events_def.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/events_def.cpp.o
.PHONY : src/events_def.cpp.o

src/events_def.i: src/events_def.cpp.i

.PHONY : src/events_def.i

# target to preprocess a source file
src/events_def.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/events_def.cpp.i
.PHONY : src/events_def.cpp.i

src/events_def.s: src/events_def.cpp.s

.PHONY : src/events_def.s

# target to generate assembly for a file
src/events_def.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/events_def.cpp.s
.PHONY : src/events_def.cpp.s

src/ledEventHandler.o: src/ledEventHandler.cpp.o

.PHONY : src/ledEventHandler.o

# target to build an object file
src/ledEventHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ledEventHandler.cpp.o
.PHONY : src/ledEventHandler.cpp.o

src/ledEventHandler.i: src/ledEventHandler.cpp.i

.PHONY : src/ledEventHandler.i

# target to preprocess a source file
src/ledEventHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ledEventHandler.cpp.i
.PHONY : src/ledEventHandler.cpp.i

src/ledEventHandler.s: src/ledEventHandler.cpp.s

.PHONY : src/ledEventHandler.s

# target to generate assembly for a file
src/ledEventHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ledEventHandler.cpp.s
.PHONY : src/ledEventHandler.cpp.s

src/ledModule.o: src/ledModule.cpp.o

.PHONY : src/ledModule.o

# target to build an object file
src/ledModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ledModule.cpp.o
.PHONY : src/ledModule.cpp.o

src/ledModule.i: src/ledModule.cpp.i

.PHONY : src/ledModule.i

# target to preprocess a source file
src/ledModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ledModule.cpp.i
.PHONY : src/ledModule.cpp.i

src/ledModule.s: src/ledModule.cpp.s

.PHONY : src/ledModule.s

# target to generate assembly for a file
src/ledModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ledModule.cpp.s
.PHONY : src/ledModule.cpp.s

src/lightModule.o: src/lightModule.cpp.o

.PHONY : src/lightModule.o

# target to build an object file
src/lightModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/lightModule.cpp.o
.PHONY : src/lightModule.cpp.o

src/lightModule.i: src/lightModule.cpp.i

.PHONY : src/lightModule.i

# target to preprocess a source file
src/lightModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/lightModule.cpp.i
.PHONY : src/lightModule.cpp.i

src/lightModule.s: src/lightModule.cpp.s

.PHONY : src/lightModule.s

# target to generate assembly for a file
src/lightModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/lightModule.cpp.s
.PHONY : src/lightModule.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/soundEventHandler.o: src/soundEventHandler.cpp.o

.PHONY : src/soundEventHandler.o

# target to build an object file
src/soundEventHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/soundEventHandler.cpp.o
.PHONY : src/soundEventHandler.cpp.o

src/soundEventHandler.i: src/soundEventHandler.cpp.i

.PHONY : src/soundEventHandler.i

# target to preprocess a source file
src/soundEventHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/soundEventHandler.cpp.i
.PHONY : src/soundEventHandler.cpp.i

src/soundEventHandler.s: src/soundEventHandler.cpp.s

.PHONY : src/soundEventHandler.s

# target to generate assembly for a file
src/soundEventHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/soundEventHandler.cpp.s
.PHONY : src/soundEventHandler.cpp.s

src/soundModule.o: src/soundModule.cpp.o

.PHONY : src/soundModule.o

# target to build an object file
src/soundModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/soundModule.cpp.o
.PHONY : src/soundModule.cpp.o

src/soundModule.i: src/soundModule.cpp.i

.PHONY : src/soundModule.i

# target to preprocess a source file
src/soundModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/soundModule.cpp.i
.PHONY : src/soundModule.cpp.i

src/soundModule.s: src/soundModule.cpp.s

.PHONY : src/soundModule.s

# target to generate assembly for a file
src/soundModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/soundModule.cpp.s
.PHONY : src/soundModule.cpp.s

src/timeModule.o: src/timeModule.cpp.o

.PHONY : src/timeModule.o

# target to build an object file
src/timeModule.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/timeModule.cpp.o
.PHONY : src/timeModule.cpp.o

src/timeModule.i: src/timeModule.cpp.i

.PHONY : src/timeModule.i

# target to preprocess a source file
src/timeModule.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/timeModule.cpp.i
.PHONY : src/timeModule.cpp.i

src/timeModule.s: src/timeModule.cpp.s

.PHONY : src/timeModule.s

# target to generate assembly for a file
src/timeModule.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/timeModule.cpp.s
.PHONY : src/timeModule.cpp.s

src/ws2811EventHandler.o: src/ws2811EventHandler.cpp.o

.PHONY : src/ws2811EventHandler.o

# target to build an object file
src/ws2811EventHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ws2811EventHandler.cpp.o
.PHONY : src/ws2811EventHandler.cpp.o

src/ws2811EventHandler.i: src/ws2811EventHandler.cpp.i

.PHONY : src/ws2811EventHandler.i

# target to preprocess a source file
src/ws2811EventHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ws2811EventHandler.cpp.i
.PHONY : src/ws2811EventHandler.cpp.i

src/ws2811EventHandler.s: src/ws2811EventHandler.cpp.s

.PHONY : src/ws2811EventHandler.s

# target to generate assembly for a file
src/ws2811EventHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/src/ws2811EventHandler.cpp.s
.PHONY : src/ws2811EventHandler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... src/dispatchEventService.o"
	@echo "... src/dispatchEventService.i"
	@echo "... src/dispatchEventService.s"
	@echo "... src/event.o"
	@echo "... src/event.i"
	@echo "... src/event.s"
	@echo "... src/events_def.o"
	@echo "... src/events_def.i"
	@echo "... src/events_def.s"
	@echo "... src/ledEventHandler.o"
	@echo "... src/ledEventHandler.i"
	@echo "... src/ledEventHandler.s"
	@echo "... src/ledModule.o"
	@echo "... src/ledModule.i"
	@echo "... src/ledModule.s"
	@echo "... src/lightModule.o"
	@echo "... src/lightModule.i"
	@echo "... src/lightModule.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/soundEventHandler.o"
	@echo "... src/soundEventHandler.i"
	@echo "... src/soundEventHandler.s"
	@echo "... src/soundModule.o"
	@echo "... src/soundModule.i"
	@echo "... src/soundModule.s"
	@echo "... src/timeModule.o"
	@echo "... src/timeModule.i"
	@echo "... src/timeModule.s"
	@echo "... src/ws2811EventHandler.o"
	@echo "... src/ws2811EventHandler.i"
	@echo "... src/ws2811EventHandler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

